### ISSUE TITLE
Bug: (Item) Aura items with incorrect stats

### ISSUE THREAD

**Issue by Axoin** [FlashTech/LeagueBuildStats#1]
- Banner of Command (MR)
- Aegis of the Legion (MR)
- Locket of the Iron Solari (MR)
- Zeke's Herald (Life Steal)

Example: MR for aura not added. the stat should be 40 instead of 20
![2015-02-06 18_53_03-input](https://cloud.githubusercontent.com/assets/10890143/6089734/953a48aa-ae35-11e4-83c8-ed2187617acc.png)

**Comment by FlashTech** [comment]
These items are fixed as of version 0.0.1.12
