### ISSUE TITLE
Minor Bug: (Item) Will of the Ancients incorrect stats

### ISSUE THREAD

**Issue by Axoin** [FlashTech/LeagueBuildStats#3]
Not that big of a deal.
The Spell Vamp
![2015-02-06 23_56_44-league build stats 0 0 1 10 - for league of legends lol](https://cloud.githubusercontent.com/assets/10890143/6091033/d758806a-ae64-11e4-9574-b3f474b9ee49.png)

**Comment by FlashTech** [comment]
The 0.00000001 added to the Spell Vamp was intentional. The plan is to add 0.00000001 to unique passive stats so that when i do calculations I can tell it is a unique passive and the 0.00000001 will be rounded anyway.

**Comment by FlashTech** [comment]
I figured out a better way to code unique stats and removed the 0.00000001. This fill will be in version 0.0.1.12 or later
